services:

  demo-db:
    ports:
      - "5656:5432"
    image: postgres:15
    container_name: demo-db-container
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: demo-db-username
      POSTGRES_PASSWORD: demo-db-password
    networks:
      - spring-boot-data-jpa-hibernate-5-demo-network

networks:
  spring-boot-data-jpa-hibernate-5-demo-network:
    name: spring-boot-data-jpa-hibernate-5-demo-network
